// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";

export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(2269489590);
}

export function ConfigFileName(): $CancellablePromise<string> {
    return $Call.ByID(733907929);
}

export function ExportEvents(search: string): $CancellablePromise<string> {
    return $Call.ByID(3419046745, search);
}

export function GetAutostart(): $CancellablePromise<boolean> {
    return $Call.ByID(3455749179);
}

export function GetDashboard(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(2336224406);
}

export function GetEvents(search: string, limit: number): $CancellablePromise<desktop$0.EventPage> {
    return $Call.ByID(2252229875, search, limit);
}

export function GetSettings(): $CancellablePromise<desktop$0.SettingsView> {
    return $Call.ByID(3018893939);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(1687209814);
}

export function OpenDataDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3108161697);
}

export function OpenSession(sessionID: string, directory: string): $CancellablePromise<void> {
    return $Call.ByID(1275588758, sessionID, directory);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2719743713);
}

export function RefreshProjects(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(2777852827);
}

export function RetryService(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(1767759115);
}

export function SaveSettings(input: desktop$0.SettingsInput): $CancellablePromise<desktop$0.SettingsView> {
    return $Call.ByID(3784651466, input);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1760948543, enabled);
}

export function SetProjectRoute(projectID: string, enabled: boolean): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(1773420776, projectID, enabled);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3051797087);
}
