// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";

export function ClearEvents(): $CancellablePromise<void> {
    return $Call.ByID(2269489590);
}

export function ConfigFileName(): $CancellablePromise<string> {
    return $Call.ByID(733907929);
}

export function ConfirmGoalLoopComplete(loopID: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(3277248528, loopID);
}

export function CreateGoalLoop(input: desktop$0.GoalLoopInput): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(3597947391, input);
}

export function DeleteGoalLoop(loopID: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(4275652508, loopID);
}

export function ExportEvents(search: string): $CancellablePromise<string> {
    return $Call.ByID(3419046745, search);
}

export function GetAutostart(): $CancellablePromise<boolean> {
    return $Call.ByID(3455749179);
}

export function GetDashboard(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(2336224406);
}

export function GetEvents(search: string, limit: number): $CancellablePromise<desktop$0.EventPage> {
    return $Call.ByID(2252229875, search, limit);
}

export function GetGoalLoopEvents(loopID: string): $CancellablePromise<desktop$0.GoalLoopEventView[] | null> {
    return $Call.ByID(1674797394, loopID);
}

export function GetGoalLoops(): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(1624491852);
}

export function GetGoalModels(): $CancellablePromise<desktop$0.GoalModelView[] | null> {
    return $Call.ByID(2905334567);
}

export function GetSettings(): $CancellablePromise<desktop$0.SettingsView> {
    return $Call.ByID(3018893939);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(1687209814);
}

export function OpenDataDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3108161697);
}

export function OpenLoopGuide(): $CancellablePromise<void> {
    return $Call.ByID(4173064136);
}

export function OpenSession(sessionID: string, directory: string): $CancellablePromise<void> {
    return $Call.ByID(1275588758, sessionID, directory);
}

export function PauseGoalLoop(loopID: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(531823213, loopID);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2719743713);
}

export function RefreshProjects(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(2777852827);
}

export function ReplyLoopPermission(requestID: string, directory: string, decision: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(3485617427, requestID, directory, decision);
}

export function ReplyLoopQuestion(input: desktop$0.QuestionReplyInput): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(1140528592, input);
}

export function ResumeGoalLoop(loopID: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(4207873420, loopID);
}

export function RetryService(): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(1767759115);
}

export function SaveSettings(input: desktop$0.SettingsInput): $CancellablePromise<desktop$0.SettingsView> {
    return $Call.ByID(3784651466, input);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1760948543, enabled);
}

export function SetProjectRoute(projectID: string, enabled: boolean): $CancellablePromise<desktop$0.Dashboard> {
    return $Call.ByID(1773420776, projectID, enabled);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3051797087);
}

export function StartGoalLoop(loopID: string, goalCommandConfirmed: boolean): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(1989153699, loopID, goalCommandConfirmed);
}

export function TerminateGoalLoop(loopID: string): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(3473154644, loopID);
}

export function UpdateGoalLoop(loopID: string, input: desktop$0.GoalLoopInput): $CancellablePromise<desktop$0.GoalLoopPage> {
    return $Call.ByID(570541202, loopID, input);
}
