// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Dashboard {
    "generatedAt": string;
    "service": ServiceStatus;
    "summary": DashboardSummary;
    "projects": ProjectView[] | null;
    "sessions": SessionView[] | null;
    "executionRuns": ExecutionRunView[] | null;
    "executionSessions": ExecutionSessionView[] | null;
    "executionRetentionDays": number;
    "agents": IntegrationView[] | null;
    "channels": IntegrationView[] | null;
}

export interface DashboardSummary {
    "connectedProjects": number;
    "runningSessions": number;
    "pendingActions": number;
    "connectedChannels": number;
}

export interface EventPage {
    "items": EventView[] | null;
}

export interface EventView {
    "id": number;
    "level": string;
    "type": string;
    "source": string;
    "message": string;
    "metadata"?: { [_ in string]?: any } | null;
    "createdAt": string;
}

export interface ExecutionRunView {
    "id": number;
    "sessionId": string;
    "sessionTitle": string;
    "directory": string;
    "projectName": string;
    "durationSeconds": number;
    "startedAt": string;
    "endedAt": string;
    "endReason": string;
    "statusLabel": string;
    "active": boolean;
}

export interface ExecutionSessionView {
    "sessionId": string;
    "sessionTitle": string;
    "directory": string;
    "projectName": string;
    "latestExecutionSeconds": number;
    "totalExecutionSeconds": number;
    "executionCount": number;
    "statusLabel": string;
    "active": boolean;
}

export interface FileSizes {
    "config": number;
    "store": number;
    "log": number;
}

export interface IntegrationView {
    "id": string;
    "type": string;
    "name": string;
    "status": string;
    "statusLabel": string;
    "endpoint": string;
    "available": boolean;
    "comingSoon": boolean;
}

export interface Paths {
    "dataDir": string;
    "configPath": string;
    "storePath": string;
    "logPath": string;
}

export interface ProjectView {
    "id": string;
    "name": string;
    "directory": string;
    "agentId": string;
    "agentName": string;
    "channelId": string;
    "channelName": string;
    "routeEnabled": boolean;
    "status": string;
    "lastSeen": string;
    "lastConversationAt": string;
}

export interface ServiceStatus {
    "state": string;
    "message": string;
    "engineRunning": boolean;
    "openCodeOnline": boolean;
    "feishuConnected": boolean;
    "feishuState": string;
    "feishuMessage": string;
    "configValid": boolean;
    "openCodeUrl": string;
}

export interface SessionView {
    "id": string;
    "title": string;
    "projectName": string;
    "directory": string;
    "agentName": string;
    "channelName": string;
    "status": string;
    "statusLabel": string;
    "statusDetail": string;
    "routeEnabled": boolean;
    "updatedAt": string;
    "busyForSeconds": number;
    "sinceLastInputSeconds": number;
    "lastInput": string;
    "hasLastInput": boolean;
    "currentModel": string;
    "currentVariant": string;
    "latestExecutionSeconds": number;
    "totalExecutionSeconds": number;
    "executionCount": number;
}

export interface SettingsInput {
    "openCodeBaseUrl": string;
    "openCodeDirectory": string;
    "openCodeUsername": string;
    "openCodePassword": string;
    "clearOpenCodePassword": boolean;
    "allowRemote": boolean;
    "feishuAppId": string;
    "feishuAppSecret": string;
    "feishuChatId": string;
    "allowedUsers": string[] | null;
    "pollingInterval": string;
    "maxOutputChars": number;
    "notifyIdle": boolean;
    "notifyError": boolean;
    "notifyQuestion": boolean;
    "notifyPermission": boolean;
    "loggingLevel": string;
    "executionRetentionDays": number;
}

export interface SettingsView {
    "paths": Paths;
    "fileSizes": FileSizes;
    "openCodeBaseUrl": string;
    "openCodeDirectory": string;
    "openCodeUsername": string;
    "openCodePasswordSet": boolean;
    "allowRemote": boolean;
    "feishuAppId": string;
    "feishuAppSecretSet": boolean;
    "feishuChatId": string;
    "allowedUsers": string[] | null;
    "pollingInterval": string;
    "maxOutputChars": number;
    "notifyIdle": boolean;
    "notifyError": boolean;
    "notifyQuestion": boolean;
    "notifyPermission": boolean;
    "loggingLevel": string;
    "executionRetentionDays": number;
    "environmentOverrides": { [_ in string]?: string } | null;
    "configError": string;
}
