// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApprovalOptionView {
    "label": string;
    "description": string;
}

export interface ApprovalQuestionView {
    "question": string;
    "header": string;
    "options": ApprovalOptionView[] | null;
    "multiple": boolean;
    "custom": boolean;
}

export interface Dashboard {
    "generatedAt": string;
    "service": ServiceStatus;
    "summary": DashboardSummary;
    "projects": ProjectView[] | null;
    "sessions": SessionView[] | null;
    "executionRuns": ExecutionRunView[] | null;
    "executionSessions": ExecutionSessionView[] | null;
    "executionRetentionDays": number;
    "agents": IntegrationView[] | null;
    "channels": IntegrationView[] | null;
}

export interface DashboardSummary {
    "connectedProjects": number;
    "completedSessions": number;
    "pendingActions": number;
    "connectedChannels": number;
}

export interface EventPage {
    "items": EventView[] | null;
}

export interface EventView {
    "id": number;
    "level": string;
    "type": string;
    "source": string;
    "message": string;
    "metadata"?: { [_ in string]?: any } | null;
    "createdAt": string;
}

export interface ExecutionRunView {
    "id": number;
    "sessionId": string;
    "sessionTitle": string;
    "directory": string;
    "projectName": string;
    "durationSeconds": number;
    "startedAt": string;
    "endedAt": string;
    "endReason": string;
    "statusLabel": string;
    "active": boolean;
}

export interface ExecutionSessionView {
    "sessionId": string;
    "sessionTitle": string;
    "directory": string;
    "projectName": string;
    "latestExecutionSeconds": number;
    "totalExecutionSeconds": number;
    "executionCount": number;
    "statusLabel": string;
    "active": boolean;
}

export interface FileSizes {
    "config": number;
    "store": number;
    "log": number;
}

export interface GoalLoopEventView {
    "id": number;
    "type": string;
    "message": string;
    "metadata"?: { [_ in string]?: any } | null;
    "createdAt": string;
}

export interface GoalLoopInput {
    "name": string;
    "goal": string;
    "projectId": string;
    "agentId": string;
    "modelProviderId": string;
    "modelId": string;
    "modelVariant": string;
    "sessionId": string;
    "automationMode": string;
    "permissionApprovalMode": string;
    "allowedDirectories": string[] | null;
    "supervisorModelProviderId": string;
    "supervisorModelId": string;
    "supervisorModelVariant": string;
    "failureLimit": number;
    "requireCompletionConfirmation": boolean;
    "goalCommandConfirmed": boolean;
    "startNow": boolean;
}

export interface GoalLoopPage {
    "generatedAt": string;
    "loops": GoalLoopView[] | null;
    "approvals": LoopApprovalView[] | null;
}

export interface GoalLoopView {
    "id": string;
    "name": string;
    "goal": string;
    "projectId": string;
    "projectName": string;
    "directory": string;
    "agentId": string;
    "agentName": string;
    "modelProviderId": string;
    "modelId": string;
    "modelName": string;
    "modelVariant": string;
    "sessionId": string;
    "attachedSession": boolean;
    "automationMode": string;
    "permissionApprovalMode": string;
    "allowedDirectories": string[] | null;
    "supervisorModelProviderId": string;
    "supervisorModelId": string;
    "supervisorModelName": string;
    "supervisorModelVariant": string;
    "supervisorSessionId": string;
    "pendingRequestId": string;
    "pendingRequestType": string;
    "status": string;
    "statusLabel": string;
    "requireCompletionConfirmation": boolean;
    "failureLimit": number;
    "consecutiveFailures": number;
    "cycleCount": number;
    "lastError": string;
    "retryAt": string;
    "createdAt": string;
    "updatedAt": string;
    "completedAt": string;
}

export interface GoalModelView {
    "providerId": string;
    "providerName": string;
    "id": string;
    "name": string;
    "variants": string[] | null;
}

export interface GoalSuggestionInput {
    "sessionId": string;
    "directory": string;
    "modelProviderId": string;
    "modelId": string;
    "modelVariant": string;
}

export interface IntegrationView {
    "id": string;
    "type": string;
    "name": string;
    "status": string;
    "statusLabel": string;
    "endpoint": string;
    "available": boolean;
    "comingSoon": boolean;
}

export interface LoopApprovalView {
    "id": string;
    "type": string;
    "sessionId": string;
    "loopId": string;
    "autonomous": boolean;
    "projectName": string;
    "directory": string;
    "questions": ApprovalQuestionView[] | null;
    "permissionName": string;
    "patterns": string[] | null;
}

export interface Paths {
    "dataDir": string;
    "configPath": string;
    "storePath": string;
    "logPath": string;
}

export interface ProjectView {
    "id": string;
    "name": string;
    "directory": string;
    "agentId": string;
    "agentName": string;
    "channelId": string;
    "channelName": string;
    "routeEnabled": boolean;
    "status": string;
    "lastSeen": string;
    "lastConversationAt": string;
}

export interface QuestionReplyInput {
    "requestId": string;
    "directory": string;
    "answers": (string[] | null)[] | null;
    "reject": boolean;
}

export interface ServiceStatus {
    "state": string;
    "message": string;
    "engineRunning": boolean;
    "openCodeOnline": boolean;
    "feishuConnected": boolean;
    "feishuState": string;
    "feishuMessage": string;
    "feishuPairingRequired": boolean;
    "feishuPairingCode": string;
    "configValid": boolean;
    "openCodeUrl": string;
}

export interface SessionModelView {
    "providerId": string;
    "modelId": string;
    "variant": string;
}

export interface SessionView {
    "id": string;
    "title": string;
    "projectName": string;
    "directory": string;
    "agentName": string;
    "channelName": string;
    "status": string;
    "statusLabel": string;
    "statusDetail": string;
    "routeEnabled": boolean;
    "updatedAt": string;
    "busyForSeconds": number;
    "sinceLastInputSeconds": number;
    "lastInput": string;
    "hasLastInput": boolean;
    "currentModel": string;
    "currentVariant": string;
    "latestExecutionSeconds": number;
    "totalExecutionSeconds": number;
    "executionCount": number;
    "goalLoopId": string;
    "goalLoopActive": boolean;
}

export interface SettingsInput {
    "openCodeBaseUrl": string;
    "openCodeDirectory": string;
    "openCodeUsername": string;
    "openCodePassword": string;
    "clearOpenCodePassword": boolean;
    "allowRemote": boolean;
    "feishuAppId": string;
    "feishuAppSecret": string;
    "feishuChatId": string;
    "allowedUsers": string[] | null;
    "pollingInterval": string;
    "maxOutputChars": number;
    "notifyIdle": boolean;
    "notifyError": boolean;
    "notifyQuestion": boolean;
    "notifyPermission": boolean;
    "loggingLevel": string;
    "executionRetentionDays": number;
}

export interface SettingsView {
    "paths": Paths;
    "fileSizes": FileSizes;
    "openCodeBaseUrl": string;
    "openCodeDirectory": string;
    "openCodeUsername": string;
    "openCodePasswordSet": boolean;
    "allowRemote": boolean;
    "feishuAppId": string;
    "feishuAppSecretSet": boolean;
    "feishuChatId": string;
    "allowedUsers": string[] | null;
    "pollingInterval": string;
    "maxOutputChars": number;
    "notifyIdle": boolean;
    "notifyError": boolean;
    "notifyQuestion": boolean;
    "notifyPermission": boolean;
    "loggingLevel": string;
    "executionRetentionDays": number;
    "environmentOverrides": { [_ in string]?: string } | null;
    "configError": string;
}
